#!/bin/bash

test() {
	declare version="$1" image="$2" name="$3"
	echo "FROM python-runtime:$version" > Dockerfile
	docker build -q -t "$image" . > /dev/null
	./test "$image"
	docker rmi "$image" > /dev/null
}

main() {
	set -eo pipefail
	local tests_dir="$(dirname $BASH_SOURCE)"
	for test in $tests_dir/*/test; do
		local test_dir="$(dirname $test)"
		local test_name="$(basename $test_dir)"
		local image="test-$test_name-$RANDOM"

		cd "$test_dir"
		set -x
		
		test 2.7 "$image" "$test_name"
		test 3.4 "$image" "$test_name"

		set +x
		cd - > /dev/null
	done
}

main