#!/bin/bash

set -eo pipefail

main() {
	declare image="$1"
	local dir="$(dirname $BASH_SOURCE)"
	local output="$(docker run --rm $image which wget)"
	[[ "$output" = "/usr/bin/wget" ]] || {
		echo "!! wget is not installed"
		exit 127
	}
}

main "$@"